apiVersion: v2
name: contoso-motors
description: A Helm chart to deploy components for the Contoso Motors scenario
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: opcsimulator
    version: 0.1.0
    repository: "file://../opc-simulator"
  - name: ovms
    version: 0.1.0
    repository: "file://../ovms"
