apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contoso-motors 
  namespace: agora
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contoso-motors
  chart:
    spec:
      chart: ./chart/contoso-motors